// Chinese Words
#define 的 ->
#define 之 .
#define 注曰 、、
// Symbols
#define 。 ;
#define “ "
#define ” "
#define ‘ '
#define ’ '
#define ： :
#define 【 [
#define 】 ]
#define 、 \
// Reserved Words
#define 汇编 asm
#define 自动 auto
#define 布尔 bool
#define 中断 break
#define 要是 case
#define 抓取 catch
#define 字符 char
#define 类 class
#define 常量 const
#define 继续 continue
#define 缺省 default
#define 删除 delete
#define 做 do
#define 双精度 double
#define 否则 else
#define 枚举 enum
#define 显式 explicit
#define 访问 export
#define 外部 extern
#define 假 false
#define 浮点 float
#define 计数 for
#define 友元 friend
#define 转到 goto
#define 如果 if
#define 内联 inline
#define 整数 int
#define 长 long
#define 命名空间 namespace
#define 新建 new
#define 符号 operator
#define 私有 private
#define 保护 protected
#define 公开 public
#define 寄存 register
#define 返回 return
#define 短数 short
#define 有符号 signed
#define 静态 static
#define 结构体 struct
#define 选择 switch
#define 模板 template
#define 本尊 this
#define 抛出 throw
#define 真 true
#define 尝试 try
#define 类型定义 typedef
#define 类型名 typename
#define 联合 union
#define 无符号 unsigned
#define 使用 using
#define 虚拟 virtual
#define 空 void
#define 不稳定 volatile

